// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/tools/list-deals.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.115.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-deals.ts
var list_deals_default = defineTool({
  name: "list_deals",
  title: "List deals",
  description: "List deals in the CRM pipeline visible to the signed-in user, newest first.",
  inputSchema: {
    search: z.string().trim().optional().describe("Filter deals whose title contains this text."),
    limit: z.number().int().min(1).max(100).optional().describe("Max deals to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("deals").select("id, title, value, probability, close_date, notes, stage_id, pipeline_id, company_id, contact_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { deals: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-deal.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_deal_default = defineTool2({
  name: "create_deal",
  title: "Create deal",
  description: "Create a new deal for the signed-in user. If no stage is given, the first stage of the first available pipeline is used.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Deal title."),
    value: z2.number().nonnegative().optional().describe("Deal value in your currency."),
    stage_id: z2.string().uuid().optional().describe("Pipeline stage id (see list_pipelines)."),
    close_date: z2.string().optional().describe("Expected close date, YYYY-MM-DD."),
    notes: z2.string().optional().describe("Free-form notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, value, stage_id, close_date, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    let stageId = stage_id;
    let pipelineId;
    if (stageId) {
      const { data: stage, error: error2 } = await supabase.from("pipeline_stages").select("id, pipeline_id").eq("id", stageId).maybeSingle();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      if (!stage) return { content: [{ type: "text", text: "Stage not found" }], isError: true };
      pipelineId = stage.pipeline_id;
    } else {
      const { data: pipeline, error: error2 } = await supabase.from("pipelines").select("id").order("created_at", { ascending: true }).limit(1).maybeSingle();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      if (!pipeline) return { content: [{ type: "text", text: "No pipeline found. Create one in the app first." }], isError: true };
      pipelineId = pipeline.id;
      const { data: stage, error: stageError } = await supabase.from("pipeline_stages").select("id").eq("pipeline_id", pipelineId).order("position", { ascending: true }).limit(1).maybeSingle();
      if (stageError) return { content: [{ type: "text", text: stageError.message }], isError: true };
      if (!stage) return { content: [{ type: "text", text: "Pipeline has no stages." }], isError: true };
      stageId = stage.id;
    }
    const { data, error } = await supabase.from("deals").insert({
      title,
      value: value ?? null,
      close_date: close_date ?? null,
      notes: notes ?? null,
      stage_id: stageId,
      pipeline_id: pipelineId,
      owner_id: userId,
      created_by: userId
    }).select().single();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { deal: data } };
  }
});

// src/lib/mcp/tools/list-pipelines.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@1.0.0";
var list_pipelines_default = defineTool3({
  name: "list_pipelines",
  title: "List pipelines and stages",
  description: "List the CRM pipelines and their stages available to the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("pipelines").select("id, name, pipeline_stages(id, name, position)").order("created_at", { ascending: true });
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { pipelines: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-contacts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_contacts_default = defineTool4({
  name: "list_contacts",
  title: "List contacts",
  description: "List CRM contacts visible to the signed-in user, optionally filtered by name or email.",
  inputSchema: {
    search: z3.string().trim().optional().describe("Filter by first name, last name, or email."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max contacts to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contacts").select("id, first_name, last_name, email, phone, position, tags, company_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (search) {
      const q = `%${search}%`;
      query = query.or(`first_name.ilike.${q},last_name.ilike.${q},email.ilike.${q}`);
    }
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { contacts: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-contact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z4 } from "npm:zod@^3.25.76";
var create_contact_default = defineTool5({
  name: "create_contact",
  title: "Create contact",
  description: "Create a new CRM contact owned by the signed-in user.",
  inputSchema: {
    first_name: z4.string().trim().min(1),
    last_name: z4.string().trim().min(1),
    email: z4.string().trim().email().optional(),
    phone: z4.string().trim().optional(),
    position: z4.string().trim().optional(),
    company_id: z4.string().uuid().optional().describe("Existing company id, if any.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ first_name, last_name, email, phone, position, company_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("contacts").insert({
      first_name,
      last_name,
      email: email ?? null,
      phone: phone ?? null,
      position: position ?? null,
      company_id: company_id ?? null,
      created_by: ctx.getUserId()
    }).select().single();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { contact: data } };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool6({
  name: "list_tasks",
  title: "List tasks",
  description: "List the signed-in user's CRM tasks, optionally only the open ones.",
  inputSchema: {
    only_open: z5.boolean().optional().describe("Return only tasks that are not completed."),
    limit: z5.number().int().min(1).max(100).optional().describe("Max tasks to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_open, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("tasks").select("id, title, description, due_date, priority, completed, deal_id, contact_id, created_at").order("due_date", { ascending: true, nullsFirst: false }).limit(limit ?? 25);
    if (only_open) query = query.eq("completed", false);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { tasks: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z6 } from "npm:zod@^3.25.76";
var create_task_default = defineTool7({
  name: "create_task",
  title: "Create task",
  description: "Create a CRM task for the signed-in user, optionally linked to a deal or contact.",
  inputSchema: {
    title: z6.string().trim().min(1),
    description: z6.string().trim().optional(),
    due_date: z6.string().optional().describe("Due date, YYYY-MM-DD."),
    priority: z6.enum(["low", "medium", "high"]).optional().describe("Defaults to medium."),
    deal_id: z6.string().uuid().optional(),
    contact_id: z6.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, due_date, priority, deal_id, contact_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").insert({
      title,
      description: description ?? null,
      due_date: due_date ?? null,
      priority: priority ?? "medium",
      deal_id: deal_id ?? null,
      contact_id: contact_id ?? null,
      user_id: ctx.getUserId()
    }).select().single();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { task: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bjhinydqkribevalvsjw";
var mcp_default = defineMcp({
  name: "mycrm",
  title: "MyCRM",
  version: "0.1.0",
  instructions: "Tools for the MyCRM sales CRM. Read and create deals, contacts and tasks, and inspect pipelines and their stages. All calls act as the signed-in CRM user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_pipelines_default,
    list_deals_default,
    create_deal_default,
    list_contacts_default,
    create_contact_default,
    list_tasks_default,
    create_task_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@1.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
